# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.subtitle }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rating Miserable Materials
subtitle: Material from Competitive Programming in UNI-FC
description: do panic
baseurl: "/RMClasses"
timezone: Peru 
sidebar_repository_limit: 3
publication_date: 2022
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
  sort_field: 'date'
  sort_reverse: true

# Uncomment the line below if you use this theme as a GitHub Page's remote theme.
remote_theme: Akash-Sharma-1/blog

# Author settings
author: Rating Miserable
organization: UNI university
location: Lima, Peru
social:
  github: peon-pasado

# Build settings (https://help.github.com/en/articles/configuring-jekyll)
# If you use this theme as a Github Pages's remote theme, you don't need to edit the
# content below, but still need to keep it in your blog's _config.yml.
collections:
  wiki:
    output: true
navigation:
  - name: Home
    link: /
  - name: Classification
    link: /classification/
  - name: Leetcode
    link: /leetcode/
  - name: About Me
    link: /about/
defaults:
  - scope:
      path: pages
    values:
      layout: default
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _leetcode
    values:
      layout: post
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - rouge
